/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW1;

import CONTROLLER.LoginController;
import MODEL.Usuario;
import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author edi
 */
public class loginTela extends javax.swing.JFrame {

    /**
     * Creates new form loginTela
     */
    public loginTela() {
        
        setTitle("LOGIN");
        setSize(400, 400); // Define o tamanho da janela
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false); // Impede redimensionamento da janela
       
        // Centraliza a janela no centro da tela
        setLocationRelativeTo(null);
        // Torna a janela visível
        setVisible(true);
        initComponents();
    
        olhoBot.setIcon(new ImageIcon("C:/Users/devmat/Downloads/eye-slash.png"));
    }


  //  limpar campos  
private void limparCampos() {
   campoSenhaLog.setText("");
}// fim limpar campos
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLog = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logarLog = new javax.swing.JButton();
        emailnome = new javax.swing.JLabel();
        nomeSenha = new javax.swing.JLabel();
        campoEmailLog = new javax.swing.JTextField();
        campoSenhaLog = new javax.swing.JPasswordField();
        olhoBot = new javax.swing.JButton();
        estiloAzul = new javax.swing.JTextField();
        estiloAzul1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        criarLogin = new javax.swing.JButton();
        imgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelLog.setBackground(new java.awt.Color(232, 228, 228));
        panelLog.setForeground(new java.awt.Color(255, 255, 255));
        panelLog.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelLog.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 160, 214, 171));

        logarLog.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logarLog.setText("OK");
        logarLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logarLogActionPerformed(evt);
            }
        });
        panelLog.add(logarLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 408, 118, -1));

        emailnome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailnome.setText("Email: ");
        panelLog.add(emailnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 278, -1, -1));

        nomeSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        nomeSenha.setText("Senha :");
        panelLog.add(nomeSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 337, -1, -1));

        campoEmailLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailLogActionPerformed(evt);
            }
        });
        panelLog.add(campoEmailLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 282, 238, -1));
        panelLog.add(campoSenhaLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 341, 193, -1));

        olhoBot.setForeground(new java.awt.Color(102, 255, 102));
        olhoBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/eye.png"))); // NOI18N
        olhoBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                olhoBotActionPerformed(evt);
            }
        });
        panelLog.add(olhoBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 39, 22));

        estiloAzul.setBackground(new java.awt.Color(51, 102, 0));
        panelLog.add(estiloAzul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 632, 1000, 68));

        estiloAzul1.setBackground(new java.awt.Color(51, 102, 0));
        panelLog.add(estiloAzul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 64));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Bem Vindo ao Login");
        panelLog.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("NutriHospitalar");
        panelLog.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 340, -1));

        criarLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/danger.png"))); // NOI18N
        criarLogin.setText("Criar Usuario");
        criarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarLoginActionPerformed(evt);
            }
        });
        panelLog.add(criarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 140, 40));

        imgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Nutri.png"))); // NOI18N
        panelLog.add(imgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 66, 1000, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logarLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logarLogActionPerformed
         
    String email = campoEmailLog.getText();
    String senha = new String(campoSenhaLog.getPassword()); // Supondo que você esteja usando um JPasswordField

    LoginController loginController = new LoginController();
    Usuario usuario = loginController.validarUsuario(email, senha);

    if (usuario != null) {
        if ("Estoquista".equals(usuario.getTipoUsuario())) {
            // Redirecionar para Telaerror
            new TelaEstoque().setVisible(true);
        } else if ("Nutricionista".equals(usuario.getTipoUsuario())) {
            // Redirecionar para TelaNutriErro
            new TelaNutricionista().setVisible(true);
        }
        this.dispose(); // Fecha a tela de loginS
    } else {
        JOptionPane.showMessageDialog(this, "Usuário ou senha inválidos.");
    }

        
    }//GEN-LAST:event_logarLogActionPerformed
boolean oculto = true;
    private void olhoBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_olhoBotActionPerformed
        // TODO add your handling code here:
        //se senha wstiver oculta
        if (oculto==true){
            campoSenhaLog.setEchoChar((char)0);//desocultar senha
            oculto=false;
            olhoBot.setIcon(new ImageIcon("C:/Users/devmat/Downloads/eye-slash.png"));
        }else{ //se senha não estiver oculta
            // \u25A0 - quadrado \u2022 - bolinha

            campoSenhaLog.setEchoChar('\u2022');//ocultar senha
            oculto=true;// senha oculta novamente
            olhoBot.setIcon(new ImageIcon("C:/Users/devmat/Downloads/eye-scan-lock.png"));
        }// fim do else
    }//GEN-LAST:event_olhoBotActionPerformed

    private void campoEmailLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailLogActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoEmailLogActionPerformed

    private void criarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarLoginActionPerformed
        // TODO add your handling code here:
        TelaAviso aviso = new TelaAviso();
        aviso.setVisible(true);
        //login.setVisible(false);
        dispose();
    }//GEN-LAST:event_criarLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoEmailLog;
    private javax.swing.JPasswordField campoSenhaLog;
    private javax.swing.JButton criarLogin;
    private javax.swing.JLabel emailnome;
    private javax.swing.JTextField estiloAzul;
    private javax.swing.JTextField estiloAzul1;
    private javax.swing.JLabel imgFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logarLog;
    private javax.swing.JLabel nomeSenha;
    private javax.swing.JButton olhoBot;
    private javax.swing.JPanel panelLog;
    // End of variables declaration//GEN-END:variables
}
