/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW1;

import CONTROLLER.DietasController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
//import Model.Chave;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edi
 */
public class TelaInfoNutri extends javax.swing.JFrame {

    /**
     * Creates new form TelaInfoNutri
     */
     int idChave;
    public TelaInfoNutri() {
        initComponents();
           listarFinalizadas();
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

 void listarFinalizadas() {
   try {
        // Criar o controlador para acessar os dados das reservas
        DietasController dietasController = new DietasController();

        // Obter os dados das reservas
        List<Object[]> dadosFinalizada = dietasController.getDadosFinalizada();

        // Obter o modelo da tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) informacaoPaciente.getModel();

        // Limpar a tabela antes de adicionar novos dados
        modeloTabela.setRowCount(0);

        // Adicionar cada linha de dados à tabela
        for (Object[] linha : dadosFinalizada) {
            modeloTabela.addRow(linha);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao atualizar a tabela: " + e.getMessage());
    }
}




private void atualizarTableActionPerformed() {
   DietasController dietasController = new DietasController();
    boolean sucesso = dietasController.informacaoPaciente();

    if (sucesso) {
        listarFinalizadas(); // Chama o método para listar as reservas e atualizar a tabela
    } else {
        JOptionPane.showMessageDialog(this, "Erro ao atualizar a tabela.");
    }
}





    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        topoLogo = new javax.swing.JTextField();
        tabelaProduto = new javax.swing.JScrollPane();
        informacaoPaciente = new javax.swing.JTable();
        Fechar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(400, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(400, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Presquições Infos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 160, 30));

        topoLogo.setBackground(new java.awt.Color(51, 102, 0));
        topoLogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topoLogoActionPerformed(evt);
            }
        });
        jPanel1.add(topoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-9, 0, 1000, 40));

        informacaoPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Paciente", "NOME do Paciente", "leito", "Dieta", "Data", "Hora", "Responsavel", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        informacaoPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                informacaoPacienteMouseClicked(evt);
            }
        });
        tabelaProduto.setViewportView(informacaoPaciente);

        jPanel1.add(tabelaProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 990, 440));

        Fechar1.setBackground(new java.awt.Color(0, 102, 0));
        Fechar1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Fechar1.setForeground(new java.awt.Color(255, 255, 255));
        Fechar1.setText("FECHAR");
        Fechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Fechar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Fechar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 140, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void topoLogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topoLogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_topoLogoActionPerformed

    private void informacaoPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_informacaoPacienteMouseClicked

    // CAPTURAR QUAL LINHA O USUÁRIO CLICOU
    int linhaSelecionada = informacaoPaciente.getSelectedRow();

    // verificando se alguma linha foi selecionada
    if (linhaSelecionada >= 0) {
        // definir modelo default para a tabela
        DefaultTableModel modeloTabela = (DefaultTableModel) informacaoPaciente.getModel();
        
        // Jogando os dados da tabela para os campos de texto, verificando se não são null
        Object idChaveObj = modeloTabela.getValueAt(linhaSelecionada, 0);
        Object nomeChaveObj = modeloTabela.getValueAt(linhaSelecionada, 1);
        Object disponibilidadeObj = modeloTabela.getValueAt(linhaSelecionada, 2);

        if (idChaveObj != null) {
            idChave = Integer.parseInt(idChaveObj.toString());
        } else {
            idChave = -1; // ou algum valor padrão que indica ausência de valor
        }
        
        if (nomeChaveObj != null) {
            nomeChave1.setText(nomeChaveObj.toString());
        } else {
            nomeChave1.setText(""); // ou algum valor padrão
        }
        
        if (disponibilidadeObj != null) {
            disponibilidade.setText(disponibilidadeObj.toString());
        } else {
            disponibilidade.setText(""); // ou algum valor padrão
        }
    }
*/
    }//GEN-LAST:event_informacaoPacienteMouseClicked

    private void Fechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Fechar1ActionPerformed
        // TODO add your handling code here:
      // cadastrarUsuario.setVisible(false);
      //panelModificar.setVisible(false);
     // panelMenuCooped.setVisible(true);

    }//GEN-LAST:event_Fechar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInfoNutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInfoNutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInfoNutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInfoNutri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInfoNutri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Fechar1;
    private javax.swing.JTable informacaoPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane tabelaProduto;
    private javax.swing.JTextField topoLogo;
    // End of variables declaration//GEN-END:variables
}
